[package]
name = "systemcontrol"
description= "Control part of the system with a cli."
version = "0.1.0"
authors = ["Simon M. <git@simon.marache.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
